# Generated by Django 4.2.5 on 2023-10-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
